index page with showing only the password
Rogozin-high-school/lab_control_panel pull request #11
Opened 2018-03-15 09:29 UTC by StavAlush27

i added a split to the data

2018-03-15 10:11 UTC, yotam180 requested changes
Left some comments for code quality assurance.

2018-03-15 10:11 UTC, yotam180 commented on lab2/lab2/index.py
> +    return 200,{"Content-type":"text/html"},data[0] #return_code,headers,code of the page(here it is html)
Operator spacing (e.g. `200, {"....": "..."}, data[0]`)

2018-03-15 10:11 UTC, yotam180 commented on lab2/lab2/index.py
> +    data=(str(post(req))).split('&')
Again — operator spacing.
And also remove the unnecessary parentheses wrapping `str(post(req))`

Also, do you really want to treat your `data` as `bytes` and not as a `str`?

2018-03-16 14:13 UTC, nofearOnline commented
please leave it for now and write the report as mentioned in the issue

2018-03-21 13:08 UTC, nofearOnline commented
it has already done so I close the issue

2018-03-21 13:08 UTC, closed without merging